spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        taxitrips-in:
          destination: taxitrips
          contentType: application/json
        taxitrips-out:
          destination: taxitrips
          contentType: application/json